# Augmented Assignment. Suppose a is assigned the value 2. What is the value of a  (not what is returned from executing the expression) after each of the following. MAKE SURE to set a back to 2 for EACH PART                                                               (10 points)
#
# 	Predict what will be generated by each math expression
# 	Type your prediction in place of the ___ in each line
#   Run the code
#   Explain any differences between your prediction and the result you got or ask a question.

def main():
    ## part a
    a = 2
    a + 3
    print(f"Prediction: a  = ____, Actual: {a}")

    ## part b
    a = 2
    a * 2
    print(f"Prediction: a  = ____, Actual: {a}")

    ## part c
    a = 2
    a += 3
    print(f"Prediction: a  = ____, Actual: {a}")

    ## part d
    a = 2
    a *= 2
    print(f"Prediction: a  = ____, Actual: {a}")

    ## part e
    a = 2
    a -= a
    print(f"Prediction: a  = ____, Actual: {a}")


if __name__ == "__main__":
    main()

