# String Concatenation and Indexing. Predict the result of each of the following, and verify your answer.          (5 points)
#
# 	Predict what will be generated by each math expression
# 	Type your prediction in place of the ___ in each line
# 	Copy the code to your development environment and run it.
# 	Explain any differences between your prediction and the result you got or ask a question.

def main():
    print("Monty" + "Python"[1], "Expected Result: ____")
    print(("Monty" + "Python")[1], "Expected Result: ____")
    print("snap"[3] + "snap"[2] + "snap"[1] + "snap"[0], "Expected Result: ____")
    print("Python"[-2], "Expected Result: ____")
    print("Atanasoff"[5 : 8], "Expected Result: ____")


if __name__ == "__main__":
    main()
