# 3.	Arithmetic Operators.
#       Predict the result of each of the following in Python.
#       Then verify if you are correct. Notice the difference between
#       // (Integer Division) and / (Floating Point Division).
# 	Predict what will be generated by each math expression
# 	Type your prediction in place of the ___ in each line
# 	Run it in CodeGrade
# 	Explain any differences between your prediction
#       and the result you got or ask a question as comments in
#       your code
# 	Some of these will generate errors – comment them out
#       and state why an error occurred.
#                                                                                             (10 points)

print(3 + 5 + 2, "Expected result is ___")
print(4 + 10 * 2, "Expected result is ___")
print((4 + 10) * 2, "Expected result is ___")
print(3 * 2 ** 3), "Expected result is ___)"
print((3 * 2) ** 3, "Expected result is ___")
print(5 / 2, "Expected result is ___")
print(5 // 2, "Expected result is ___")
print(2 / 0, "Expected result is ___")
print((1 / (3 // 2)), "Expected result is ___")
print(1 / 3 // 2,  "Expected result is ___")
